import { useState } from 'react';
import { Check, FileText, MapPin, ShieldCheck, Star, X } from 'lucide-react';
import { getListAdminDriversQueryKey, useListAdminDrivers, useReviewDriver } from '@workspace/api-client-react';
import type { Driver } from '@workspace/api-client-react';
import { ActionButton, EmptyState, ErrorState, LoadingState, MetricCard, PageIntro, StatusPill, SuccessNotice } from '@/components/travel-ui';
import { useQueryClient } from '@tanstack/react-query';

export default function Admin() {
  const drivers = useListAdminDrivers({ query: { queryKey: getListAdminDriversQueryKey(), staleTime: 60_000 } });
  const review = useReviewDriver();
  const queryClient = useQueryClient();
  const [notice, setNotice] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const decide = (driver: Driver, status: 'approved' | 'rejected') => { setNotice(null); setBusyId(driver.id); review.mutate({ id: driver.id, data: { status } }, { onSuccess: () => { setNotice(`${driver.name} ${status === 'approved' ? 'εγκρίθηκε' : 'απορρίφθηκε'} επιτυχώς.`); setBusyId(null); queryClient.invalidateQueries({ queryKey: getListAdminDriversQueryKey() }); }, onError: () => { setBusyId(null); setNotice('Η ενέργεια δεν ολοκληρώθηκε. Δοκίμασε ξανά.'); } }); };
  return <div className="min-h-[calc(100dvh-72px)] bg-[#f0eee8] px-5 py-8 md:px-10 md:py-12"><div className="mx-auto max-w-[1280px]"><PageIntro eyebrow="Operations / Admin" title="Οι σωστοί άνθρωποι, στο τιμόνι." detail="Έλεγξε τα στοιχεία των νέων συνεργατών και κράτησε το δίκτυο μετακινήσεων αξιόπιστο." action={<div className="flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><ShieldCheck size={15} /> Κέντρο ελέγχου</div>} /><div className="mb-7 grid gap-3 md:grid-cols-3"><MetricCard label="Προς έγκριση" value={String(drivers.data?.filter((d) => d.status === 'pending').length ?? 0).padStart(2, '0')} foot="φάκελοι σε αναμονή" accent /><MetricCard label="Μέσος χρόνος" value="18′" foot="για πλήρη έλεγχο" /><MetricCard label="Συνεργάτες" value={String(drivers.data?.length ?? 0)} foot="στο δίκτυο σήμερα" /></div>{notice && <div className="mb-5"><SuccessNotice>{notice}</SuccessNotice></div>}{drivers.isLoading ? <LoadingState label="Φορτώνουμε τους φακέλους συνεργατών…" /> : drivers.isError ? <ErrorState onRetry={() => drivers.refetch()} label="Δεν μπορέσαμε να φορτώσουμε τους οδηγούς." /> : (drivers.data ?? []).length === 0 ? <EmptyState title="Όλα τακτοποιημένα." detail="Δεν υπάρχουν οδηγοί που περιμένουν έλεγχο. Το δίκτυο είναι καθαρό." /> : <div className="overflow-hidden rounded-2xl border border-[#d8d5cc] bg-card"><div className="hidden grid-cols-[1.4fr_1fr_.8fr_.8fr_1.2fr] gap-4 border-b border-border bg-[#e7e3d8] px-5 py-3 font-mono-ui text-[10px] uppercase tracking-[.15em] text-muted-foreground md:grid"><span>Συνεργάτης</span><span>Όχημα</span><span>Εμπειρία</span><span>Φάκελος</span><span>Ενέργεια</span></div>{(drivers.data ?? []).map((driver) => <DriverRow key={driver.id} driver={driver} busy={busyId === driver.id} onDecide={decide} />)}</div>}</div></div>;
}

function DriverRow({ driver, busy, onDecide }: { driver: Driver; busy: boolean; onDecide: (driver: Driver, status: 'approved' | 'rejected') => void }) {
  const [open, setOpen] = useState(false);
  return <div className="border-b border-border p-5 last:border-b-0" data-testid={`row-driver-${driver.id}`}><div className="grid gap-4 md:grid-cols-[1.4fr_1fr_.8fr_.8fr_1.2fr] md:items-center"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#f2bf91] font-display text-sm text-primary">{driver.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div><div><p className="font-bold text-primary">{driver.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin size={12} />{driver.city}</p></div></div><div><p className="text-sm font-semibold text-primary">{driver.vehicle}</p><p className="mt-1 text-xs text-muted-foreground">{driver.vehicleType}</p></div><div className="flex items-center gap-1 text-sm text-primary"><Star size={14} className="text-accent" fill="currentColor" /> {driver.rating.toFixed(2)}<span className="ml-1 text-xs text-muted-foreground">· {driver.trips} trips</span></div><button data-testid={`button-documents-${driver.id}`} onClick={() => setOpen(!open)} className="flex items-center gap-2 text-sm font-bold text-primary hover:text-accent"><FileText size={16} /> {driver.documents} αρχεία</button><div className="flex gap-2">{driver.status === 'pending' ? <><ActionButton data-testid={`button-approve-driver-${driver.id}`} onClick={() => onDecide(driver, 'approved')} disabled={busy} loading={busy} className="bg-[#32795d] px-3 py-2 text-xs hover:bg-[#276349]"><Check size={14} /> Έγκριση</ActionButton><button data-testid={`button-reject-driver-${driver.id}`} onClick={() => onDecide(driver, 'rejected')} disabled={busy} className="grid h-9 w-9 place-items-center rounded-xl border border-[#e5b2aa] text-[#a24d43] hover:bg-[#fff3f0]"><X size={16} /></button></> : <StatusPill status={driver.status} />}</div></div>{open && <div className="mt-4 rounded-xl bg-muted/60 p-4 text-xs text-muted-foreground" data-testid={`details-driver-${driver.id}`}><p className="font-bold text-primary">Έγγραφα προς επαλήθευση</p><p className="mt-2">Άδεια οδήγησης · Άδεια κυκλοφορίας · Ασφάλιση οχήματος · {driver.documents} συνολικά αρχεία</p></div>}</div>;
}