uploads = []
generated = []

[[outputs]]
id = "ndmFEX0UkMywnmCIC5lDY"
uri = "file://exports/aperion-travel-experiences.html"
type = "text"
title = "Aperion Travel Experiences — HTML"
description = "Αυτόνομο offline HTML αρχείο. Κατέβασέ το και άνοιξέ το με διπλό κλικ στον υπολογιστή σου."
logical_id = "492ce4a1-bb3c-4ced-880b-74ef00b827d4"
content_hash = "sha256:83e1499c35699cfdda8ad440801d35b2c5b961b5f105ff339f269a4763f321d2"
size = 51998
mtime_ms = 1788119198156
storage_uri = "gcs://replit-rams-assets-spock/rams/assets/repl:9e53aa2c-c750-46ed-ab3c-fdfb5ecbae98/492ce4a1-bb3c-4ced-880b-74ef00b827d4/436441e9-1c9a-419b-a776-05797050ad45"
storage_version_token = "1788119212983433"
content_type = "text/html"
